### ISSUE TITLE
Parse settings page to get probe count

### ISSUE THREAD

**Issue by LordMike** [LordMike/ogame-bot#3]
Instead of the user supplying it, get it from the settings or galaxy pages (is that even possible?)

**Comment by Tunis** [comment]
hello,

well you just need to take the value of the imput field :

`<input type="text" pattern="[0-9]*" class="textInput w50 textCenter textBeefy" value="1" size="2" maxlength="2" name="spio_anz">`

in the page :
index.php?page=preferences

just look though your code for the galaxy page, and see that you take the galaxy and system from the table and not the input :p

doing something that look like :
`elems = doc.All.GetElementsByName("spio_anz");`
then
`nbProbes = elems.GetAttribute("value");`
link :
https://msdn.microsoft.com/en-us/library/system.windows.forms.htmlelementcollection.getelementsbyname(v=vs.110).aspx

**Comment by LordMike** [comment]
Not necessary. See #2
